# docker-compose -f docker-compose.windows.yml build
# docker run -d -p 1433:1433 -e sa_password=Password123! -e ACCEPT_EULA=Y -v C:/data/:C:/data/ -e attach_dbs="[{'dbName':'ApiDev','dbFiles':['C:\\data\\ApiDev.mdf','C:\\data\\ApiDev_log.ldf']}]" microsoft/mssql-server-windows
version: '2.1'

networks:
  default:
    external:
      name: nat

services:
  angulartemplate-node-nano:
    build:
      context: .
      dockerfile: Dockerfile.node.nano
    environment:
      "Data Source": "mssql-server-windows;Initial Catalog=ApiDev;Integrated Security=False;User Id=sa;Password=Password123!;Connect Timeout=60;Encrypt=True"
      PORT: 80
    depends_on:
      - mssql-server-windows
    image: paulgilchrist/angulartemplate-node-nano
    ports: ["80:80"]
  mssql-server-windows:
    environment:
      ACCEPT_EULA: Y
      sa_password: Password123!
      attach_dbs: "[{'dbName':'ApiDev','dbFiles':['C:\\\\data\\\\ApiDev.mdf','C:\\\\data\\\\ApiDev_log.ldf']}]"
    expose: [1433]
    image: microsoft/mssql-server-windows
    volumes:
      - "C:/data/:C:/data/"

