apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  selector:
    matchLabels:
      app: angular-pod
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: angular-pod
        env: dev
    spec:
      containers:
        - name: front-end
          image: paulgilchrist/angular-template
          ports:
            - containerPort:
                3000
                # defines the health checking
          livenessProbe:
            # an TCP probe
            tcpSocket:
              port: 3000
            # length of time to wait for a pod to initialize after pod startup, before applying health checking
            initialDelaySeconds: 30
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
  labels:
    app: angular-service
    env: dev
spec:
  type: LoadBalancer
  ports:
    - port: 80 # the port that this service should serve on
      # the container on each pod to connect to, can be a name
      # (e.g. 'www') or a number (e.g. 80)
      targetPort: 3000
      protocol: TCP
    # just like the selector in the deployment,
    # but this time it identifies the set of pods to load balance
    # traffic to.
  selector:
    app: angular-pod
    env: dev
