#Documentation at https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/
#kubectl version
#kubectl cluster-info
#kubectl apply -f kube-deployment.yaml
#Pods are load balanced nodes. Replicasets are the load balanced cluster. Deployments are the combination of all replicasets making up and application
#Some useful commands include <delete, describe, or get> <deployments, pods, replicasets, or services> [name]
#Examples
#   kubectl get deployments angular-deployment
#   kubectl describe replicasets
apiVersion: v1
kind: Service
metadata:
  name: angular-service
  labels:
    app: angular-service
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 8081 # Exposed port on LoadBalancer
      targetPort: 80 # Container port
      protocol: TCP
  selector: # Pods to load balance traffic to
    app: angular-pod
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  selector:
    matchLabels:
      app: angular-pod
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: angular-pod
        tier: frontend
    spec:
      containers:
        - name: front-end
          image: paulgilchrist/angular-template
          ports:
            - containerPort: 80 # Must match what the Docker container exposes
          livenessProbe: # Defines the health checking
            tcpSocket: # TCP probe
              port: 80
            initialDelaySeconds: 30 # length of time to wait for a pod to initialize after pod startup, before applying health checking
            timeoutSeconds: 1
---